import { materials } from './materials'
import type { FactoryLoad } from '../types'

export const factoryLoads: FactoryLoad[] = [
  {
    id: '12ga-bis-3-125',
    label: '12ga 3in 1-1/4oz #3 Bismuth',
    gauge: 12,
    material: 'bismuth',
    shotSize: '3',
    payloadOz: 1.25,
    velocityFps: materials.bismuth.defaultVelocityFps,
    pricePerShell: 3.25,
  },
  {
    id: '12ga-tss-7-15',
    label: '12ga 3in 1-1/2oz #7 TSS',
    gauge: 12,
    material: 'tss',
    shotSize: '7',
    payloadOz: 1.5,
    velocityFps: materials.tss.defaultVelocityFps,
    pricePerShell: 5.75,
  },
  {
    id: '12ga-steel-2-125',
    label: '12ga 3in 1-1/4oz #2 Steel',
    gauge: 12,
    material: 'steel',
    shotSize: '2',
    payloadOz: 1.25,
    velocityFps: materials.steel.defaultVelocityFps,
    pricePerShell: 1.6,
  },
  {
    id: '12ga-hevi-4-1375',
    label: '12ga 3in 1-3/8oz #4 Hevi-Shot',
    gauge: 12,
    material: 'hevi',
    shotSize: '4',
    payloadOz: 1.375,
    velocityFps: materials.hevi.defaultVelocityFps,
    pricePerShell: 4.2,
  },
  {
    id: '20ga-bis-4-1',
    label: '20ga 3in 1oz #4 Bismuth',
    gauge: 20,
    material: 'bismuth',
    shotSize: '4',
    payloadOz: 1,
    velocityFps: materials.bismuth.defaultVelocityFps,
    pricePerShell: 2.8,
  },
  {
    id: '20ga-steel-3-1',
    label: '20ga 3in 1oz #3 Steel',
    gauge: 20,
    material: 'steel',
    shotSize: '3',
    payloadOz: 1,
    velocityFps: materials.steel.defaultVelocityFps,
    pricePerShell: 1.45,
  },
  {
    id: '28ga-tp-6-0875',
    label: '28ga 3in 7/8oz #6 Tungsten Polymer',
    gauge: 28,
    material: 'tungstenPolymer',
    shotSize: '6',
    payloadOz: 0.875,
    velocityFps: materials.tungstenPolymer.defaultVelocityFps,
    pricePerShell: 2.35,
  },
  {
    id: '16ga-bis-5-1125',
    label: '16ga 2-3/4in 1-1/8oz #5 Bismuth',
    gauge: 16,
    material: 'bismuth',
    shotSize: '5',
    payloadOz: 1.125,
    velocityFps: materials.bismuth.defaultVelocityFps,
    pricePerShell: 3,
  },
  {
    id: '410-tss-9-0562',
    label: '.410 3in 9/16oz #9 TSS',
    gauge: 410,
    material: 'tss',
    shotSize: '9',
    payloadOz: 0.5625,
    velocityFps: materials.tss.defaultVelocityFps,
    pricePerShell: 7,
  },
  {
    id: '12ga-lead-4-125',
    label: '12ga 2-3/4in 1-1/4oz #4 Lead',
    gauge: 12,
    material: 'lead',
    shotSize: '4',
    payloadOz: 1.25,
    velocityFps: materials.lead.defaultVelocityFps,
    pricePerShell: 1.2,
  },
]
